create table if not exists public.referral_weekly_payouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  week_start date not null,
  level integer not null check (level between 1 and 3),
  member_count integer not null check (member_count >= 8),
  amount numeric(12, 2) not null check (amount > 0),
  created_at timestamptz not null default now(),
  constraint referral_weekly_payouts_user_week_unique unique (user_id, week_start)
);

alter table public.referral_weekly_payouts enable row level security;

create or replace function public.process_weekly_referral_payouts(p_week_start date)
returns table(user_id uuid, level integer, member_count integer, amount numeric)
language plpgsql
security definer
set search_path = public
as $$
begin
  if p_week_start is null or extract(isodow from p_week_start) <> 1 then
    raise exception 'p_week_start must be a Monday';
  end if;

  return query
  with member_counts as (
    select r.referrer_id as user_id, count(distinct r.referred_id)::integer as member_count
    from public.referrals r
    where r.level = 1
    group by r.referrer_id
  ), eligible as (
    select
      mc.user_id,
      case when mc.member_count >= 24 then 3
           when mc.member_count >= 15 then 2
           else 1 end as level,
      mc.member_count,
      case when mc.member_count >= 24 then 1500
           when mc.member_count >= 15 then 800
           else 300 end::numeric(12, 2) as amount
    from member_counts mc
    where mc.member_count >= 8
  ), payouts as (
    insert into public.referral_weekly_payouts (user_id, week_start, level, member_count, amount)
    select e.user_id, p_week_start, e.level, e.member_count, e.amount
    from eligible e
    on conflict (user_id, week_start) do nothing
    returning referral_weekly_payouts.user_id, referral_weekly_payouts.level,
      referral_weekly_payouts.member_count, referral_weekly_payouts.amount
  ), ledger as (
    insert into public.transactions (user_id, type, amount, description, status)
    select p.user_id, 'referral_weekly', p.amount,
      format('Weekly referral reward: Level %s (%s members)', p.level, p.member_count),
      'completed'
    from payouts p
    returning transactions.user_id
  ), notifications as (
    insert into public.notifications (user_id, title, message, read)
    select p.user_id, 'Weekly Referral Reward',
      format('KSh %s for Level %s referral benefits has been credited.',
        to_char(p.amount, 'FM999,999,990'), p.level),
      false
    from payouts p
    returning notifications.user_id
  )
  select p.user_id, p.level, p.member_count, p.amount
  from payouts p
  join ledger l on l.user_id = p.user_id
  join notifications n on n.user_id = p.user_id;
end;
$$;

revoke all on function public.process_weekly_referral_payouts(date) from public, anon, authenticated;
grant execute on function public.process_weekly_referral_payouts(date) to service_role;